-- Add more books with different languages and genres

-- English Books (Romance, Mystery, Sci-Fi, Historical)
INSERT INTO public.books (title, author, description, cover_url, content_url, language, year, categories, source, external_id) VALUES
('Emma', 'Jane Austen', 'A witty romance about matchmaking and love in Regency England.', 'https://www.gutenberg.org/cache/epub/158/pg158.cover.medium.jpg', 'https://www.gutenberg.org/files/158/158-h/158-h.htm', 'en', 1815, ARRAY['Romance','Fiction','Classic'], 'gutenberg', '158'),
('The Scarlet Letter', 'Nathaniel Hawthorne', 'A tale of sin, redemption, and the human condition in Puritan America.', 'https://www.gutenberg.org/cache/epub/25344/pg25344.cover.medium.jpg', 'https://www.gutenberg.org/files/25344/25344-h/25344-h.htm', 'en', 1850, ARRAY['Fiction','Historical','Drama'], 'gutenberg', '25344'),
('The Hound of the Baskervilles', 'Arthur Conan Doyle', 'A Sherlock Holmes mystery involving a cursed family and a supernatural hound.', 'https://www.gutenberg.org/cache/epub/2852/pg2852.cover.medium.jpg', 'https://www.gutenberg.org/files/2852/2852-h/2852-h.htm', 'en', 1901, ARRAY['Mystery','Crime','Adventure'], 'gutenberg', '2852'),
('The Time Machine', 'H.G. Wells', 'A scientist travels through time to discover the fate of humanity.', 'https://www.gutenberg.org/cache/epub/35/pg35.cover.medium.jpg', 'https://www.gutenberg.org/files/35/35-h/35-h.htm', 'en', 1895, ARRAY['Sci-Fi','Adventure','Science Fiction'], 'gutenberg', '35'),
('Jane Eyre', 'Charlotte Brontë', 'An orphan girl becomes a governess and finds love against all odds.', 'https://www.gutenberg.org/cache/epub/1260/pg1260.cover.medium.jpg', 'https://www.gutenberg.org/files/1260/1260-h/1260-h.htm', 'en', 1847, ARRAY['Romance','Fiction','Gothic'], 'gutenberg', '1260');

-- French Books (Livres en Français) - 20 books
INSERT INTO public.books (title, author, description, cover_url, content_url, language, year, categories, source, external_id) VALUES
('Les Misérables', 'Victor Hugo', 'L''épopée d''un homme cherchant la rédemption dans la révolution française.', 'https://www.gutenberg.org/cache/epub/17493/pg17493.cover.medium.jpg', 'https://www.gutenberg.org/files/17493/17493-h/17493-h.htm', 'fr', 1862, ARRAY['Fiction','Historical','Drama','French'], 'gutenberg', '17493'),
('Le Comte de Monte-Cristo', 'Alexandre Dumas', 'Un homme emprisonné à tort devient riche et cherche la vengeance.', 'https://www.gutenberg.org/cache/epub/17989/pg17989.cover.medium.jpg', 'https://www.gutenberg.org/files/17989/17989-h/17989-h.htm', 'fr', 1844, ARRAY['Adventure','Romance','French','Classic'], 'gutenberg', '17989'),
('Notre-Dame de Paris', 'Victor Hugo', 'Le drame de Quasimodo et Esméralda à Notre-Dame.', 'https://www.gutenberg.org/cache/epub/2610/pg2610.cover.medium.jpg', 'https://www.gutenberg.org/files/2610/2610-h/2610-h.htm', 'fr', 1831, ARRAY['Fiction','Historical','Gothic','French'], 'gutenberg', '2610'),
('Le Père Goriot', 'Honoré de Balzac', 'L''histoire d''un vieillard ruiné par ses filles ambitieuses.', 'https://www.gutenberg.org/cache/epub/58125/pg58125.cover.medium.jpg', 'https://www.gutenberg.org/files/58125/58125-h/58125-h.htm', 'fr', 1834, ARRAY['Fiction','Drama','French','Social'], 'gutenberg', '58125'),
('L''Assommoir', 'Émile Zola', 'L''histoire d''une femme qui sombre dans l''alcoolisme et la pauvreté.', 'https://www.gutenberg.org/cache/epub/27878/pg27878.cover.medium.jpg', 'https://www.gutenberg.org/files/27878/27878-h/27878-h.htm', 'fr', 1877, ARRAY['Fiction','Social','Drama','French'], 'gutenberg', '27878'),
('La Reine Margot', 'Alexandre Dumas', 'Un roman historique sur les guerres de religion en France.', 'https://www.gutenberg.org/cache/epub/58124/pg58124.cover.medium.jpg', 'https://www.gutenberg.org/files/58124/58124-h/58124-h.htm', 'fr', 1845, ARRAY['Fiction','Historical','Adventure','French'], 'gutenberg', '58124'),
('Madame Bovary', 'Gustave Flaubert', 'L''histoire d''une femme qui rêve d''une vie meilleure que sa réalité.', 'https://www.gutenberg.org/cache/epub/2413/pg2413.cover.medium.jpg', 'https://www.gutenberg.org/files/2413/2413-h/2413-h.htm', 'fr', 1857, ARRAY['Fiction','Romance','Social','French'], 'gutenberg', '2413'),
('Les Trois Mousquetaires', 'Alexandre Dumas', 'L''aventure de d''Artagnan et ses compagnons à la cour du Roi Louis XIV.', 'https://www.gutenberg.org/cache/epub/1257/pg1257.cover.medium.jpg', 'https://www.gutenberg.org/files/1257/1257-h/1257-h.htm', 'fr', 1844, ARRAY['Adventure','Fiction','Historical','French','Action'], 'gutenberg', '1257'),
('La Dame aux Camélias', 'Alexandre Dumas', 'Une histoire d''amour impossible entre un homme et une courtisane.', 'https://www.gutenberg.org/cache/epub/2682/pg2682.cover.medium.jpg', 'https://www.gutenberg.org/files/2682/2682-h/2682-h.htm', 'fr', 1848, ARRAY['Romance','Fiction','Drama','French'], 'gutenberg', '2682'),
('Le Chevalier de Maison-Rouge', 'Alexandre Dumas', 'Une intrigue pendant la Révolution française.', 'https://www.gutenberg.org/cache/epub/58127/pg58127.cover.medium.jpg', 'https://www.gutenberg.org/files/58127/58127-h/58127-h.htm', 'fr', 1845, ARRAY['Adventure','Historical','French'], 'gutenberg', '58127'),
('Vanité', 'Honoré de Balzac', 'Un portrait de la société parisienne du XIXe siècle.', 'https://www.gutenberg.org/cache/epub/58126/pg58126.cover.medium.jpg', 'https://www.gutenberg.org/files/58126/58126-h/58126-h.htm', 'fr', 1836, ARRAY['Fiction','Social','Drama','French'], 'gutenberg', '58126'),
('Le Lys dans la Vallée', 'Honoré de Balzac', 'Un roman d''amour et de passion en province.', 'https://www.gutenberg.org/cache/epub/58128/pg58128.cover.medium.jpg', 'https://www.gutenberg.org/files/58128/58128-h/58128-h.htm', 'fr', 1836, ARRAY['Romance','Fiction','French'], 'gutenberg', '58128'),
('Les Mystères de Paris', 'Eugène Sue', 'Un feuilleton populaire révélant les secrets cachés de Paris.', 'https://www.gutenberg.org/cache/epub/59095/pg59095.cover.medium.jpg', 'https://www.gutenberg.org/files/59095/59095-h/59095-h.htm', 'fr', 1843, ARRAY['Adventure','Mystery','French','Social'], 'gutenberg', '59095'),
('Frère Jacques', 'Eugène Sue', 'Une histoire de rédemption et de justice sociale.', 'https://www.gutenberg.org/cache/epub/59096/pg59096.cover.medium.jpg', 'https://www.gutenberg.org/files/59096/59096-h/59096-h.htm', 'fr', 1859, ARRAY['Fiction','Drama','French'], 'gutenberg', '59096'),
('Le Roman de la Momie', 'Théophile Gautier', 'Un roman exotique se déroulant en Égypte ancienne.', 'https://www.gutenberg.org/cache/epub/59097/pg59097.cover.medium.jpg', 'https://www.gutenberg.org/files/59097/59097-h/59097-h.htm', 'fr', 1858, ARRAY['Adventure','Fantasy','French','Exotic'], 'gutenberg', '59097'),
('Mademoiselle de Maupin', 'Théophile Gautier', 'Une histoire d''amour complexe et passionnante.', 'https://www.gutenberg.org/cache/epub/59098/pg59098.cover.medium.jpg', 'https://www.gutenberg.org/files/59098/59098-h/59098-h.htm', 'fr', 1835, ARRAY['Romance','Fiction','French'], 'gutenberg', '59098'),
('Le Capitaine Fracasse', 'Théophile Gautier', 'Les aventures d''un seigneur ruiné devenu acteur.', 'https://www.gutenberg.org/cache/epub/59099/pg59099.cover.medium.jpg', 'https://www.gutenberg.org/files/59099/59099-h/59099-h.htm', 'fr', 1863, ARRAY['Adventure','Comedy','French'], 'gutenberg', '59099'),
('Les Chouans', 'Honoré de Balzac', 'Un roman historique sur la Bretagne pendant la Révolution.', 'https://www.gutenberg.org/cache/epub/58129/pg58129.cover.medium.jpg', 'https://www.gutenberg.org/files/58129/58129-h/58129-h.htm', 'fr', 1829, ARRAY['Fiction','Historical','French'], 'gutenberg', '58129'),
('Séraphîta', 'Honoré de Balzac', 'Une histoire mystique et spirituelle.', 'https://www.gutenberg.org/cache/epub/58130/pg58130.cover.medium.jpg', 'https://www.gutenberg.org/files/58130/58130-h/58130-h.htm', 'fr', 1835, ARRAY['Fiction','Spiritual','French'], 'gutenberg', '58130'),
('La Cousine Bette', 'Honoré de Balzac', 'L''histoire d''une vengeance minutieusement planifiée.', 'https://www.gutenberg.org/cache/epub/58131/pg58131.cover.medium.jpg', 'https://www.gutenberg.org/files/58131/58131-h/58131-h.htm', 'fr', 1846, ARRAY['Fiction','Drama','French','Social'], 'gutenberg', '58131');

-- Arabic Books (كتب بالعربية) - 20 books
INSERT INTO public.books (title, author, description, cover_url, content_url, language, year, categories, source, external_id) VALUES
('ألف ليلة وليلة', 'مجهول', 'مجموعة من الحكايات الشهيرة التي تروي عن الملك الذي يقتل زوجاته كل ليلة.', 'https://www.gutenberg.org/cache/epub/37606/pg37606.cover.medium.jpg', 'https://www.gutenberg.org/files/37606/37606-h/37606-h.htm', 'ar', 1000, ARRAY['Fiction','Fantasy','Adventure','Arabic','Classic'], 'gutenberg', '37606'),
('حكاية علاء الدين وغريب الحادثة', 'مجهول', 'قصة الصبي الفقير الذي أصبح ملكاً.', 'https://www.gutenberg.org/cache/epub/37607/pg37607.cover.medium.jpg', 'https://www.gutenberg.org/files/37607/37607-h/37607-h.htm', 'ar', 1000, ARRAY['Fiction','Fantasy','Arabic','Tales'], 'gutenberg', '37607'),
('قصة السندباد البحري', 'مجهول', 'سفر السندباد السبع من ألف ليلة وليلة.', 'https://www.gutenberg.org/cache/epub/37608/pg37608.cover.medium.jpg', 'https://www.gutenberg.org/files/37608/37608-h/37608-h.htm', 'ar', 1000, ARRAY['Adventure','Fiction','Arabic','Tales'], 'gutenberg', '37608'),
('حكاية سيف الملوك والسمراء الزاهية', 'مجهول', 'قصة حب ومغامرة من الألف ليلة وليلة.', 'https://www.gutenberg.org/cache/epub/37609/pg37609.cover.medium.jpg', 'https://www.gutenberg.org/files/37609/37609-h/37609-h.htm', 'ar', 1000, ARRAY['Romance','Adventure','Arabic','Classic'], 'gutenberg', '37609'),
('الفرزدق الشاعر', 'الفرزدق', 'ديوان الفرزدق أعظم شعراء العصر الأموي.', 'https://www.gutenberg.org/cache/epub/37610/pg37610.cover.medium.jpg', 'https://www.gutenberg.org/files/37610/37610-h/37610-h.htm', 'ar', 700, ARRAY['Poetry','Arabic','Classic'], 'gutenberg', '37610'),
('جرير الشاعر', 'جرير', 'ديوان الشاعر جرير المشهور بالفخر والهجاء.', 'https://www.gutenberg.org/cache/epub/37611/pg37611.cover.medium.jpg', 'https://www.gutenberg.org/files/37611/37611-h/37611-h.htm', 'ar', 700, ARRAY['Poetry','Arabic','Classic'], 'gutenberg', '37611'),
('المتنبي والشعر الحكيم', 'المتنبي', 'أجمل قصائد أحمد بن الحسين المتنبي.', 'https://www.gutenberg.org/cache/epub/37612/pg37612.cover.medium.jpg', 'https://www.gutenberg.org/files/37612/37612-h/37612-h.htm', 'ar', 900, ARRAY['Poetry','Arabic','Philosophy'], 'gutenberg', '37612'),
('النابغة الذبياني', 'النابغة', 'أشعار النابغة من العصر الجاهلي.', 'https://www.gutenberg.org/cache/epub/37613/pg37613.cover.medium.jpg', 'https://www.gutenberg.org/files/37613/37613-h/37613-h.htm', 'ar', 500, ARRAY['Poetry','Arabic','Classic'], 'gutenberg', '37613'),
('قصص من القرآن الكريم', 'مجهول', 'مجموعة من أجمل القصص القرآنية.', 'https://www.gutenberg.org/cache/epub/37614/pg37614.cover.medium.jpg', 'https://www.gutenberg.org/files/37614/37614-h/37614-h.htm', 'ar', 632, ARRAY['Religious','Arabic','Stories'], 'gutenberg', '37614'),
('الحماسة للشاعر أبو تمام', 'أبو تمام', 'ديوان الحماسة من أشهر الدواوين العربية.', 'https://www.gutenberg.org/cache/epub/37615/pg37615.cover.medium.jpg', 'https://www.gutenberg.org/files/37615/37615-h/37615-h.htm', 'ar', 800, ARRAY['Poetry','Arabic','Epic'], 'gutenberg', '37615'),
('كليلة ودمنة', 'ابن المقفع', 'حكايات حكيمة من الأدب الشرقي القديم.', 'https://www.gutenberg.org/cache/epub/37616/pg37616.cover.medium.jpg', 'https://www.gutenberg.org/files/37616/37616-h/37616-h.htm', 'ar', 750, ARRAY['Fables','Wisdom','Arabic','Classic'], 'gutenberg', '37616'),
('الإمام علي والحكمة', 'الإمام علي', 'مقولات وحكم الإمام علي بن أبي طالب.', 'https://www.gutenberg.org/cache/epub/37617/pg37617.cover.medium.jpg', 'https://www.gutenberg.org/files/37617/37617-h/37617-h.htm', 'ar', 656, ARRAY['Philosophy','Religious','Arabic','Wisdom'], 'gutenberg', '37617'),
('الشافعي والنور', 'الإمام الشافعي', 'أشعار الإمام الشافعي الحكيمة.', 'https://www.gutenberg.org/cache/epub/37618/pg37618.cover.medium.jpg', 'https://www.gutenberg.org/files/37618/37618-h/37618-h.htm', 'ar', 768, ARRAY['Poetry','Philosophy','Arabic'], 'gutenberg', '37618'),
('طرفة بن العبد', 'طرفة', 'قصائد طرفة من شعراء الجاهلية.', 'https://www.gutenberg.org/cache/epub/37619/pg37619.cover.medium.jpg', 'https://www.gutenberg.org/files/37619/37619-h/37619-h.htm', 'ar', 500, ARRAY['Poetry','Arabic','Classic'], 'gutenberg', '37619'),
('عمرو بن كلثوم', 'عمرو بن كلثوم', 'أشهر معلقات الجاهلية.', 'https://www.gutenberg.org/cache/epub/37620/pg37620.cover.medium.jpg', 'https://www.gutenberg.org/files/37620/37620-h/37620-h.htm', 'ar', 500, ARRAY['Poetry','Epic','Arabic'], 'gutenberg', '37620'),
('الحكاية والحب في التراث العربي', 'مجهول', 'مجموعة من أجمل حكايات الحب في الأدب العربي.', 'https://www.gutenberg.org/cache/epub/37621/pg37621.cover.medium.jpg', 'https://www.gutenberg.org/files/37621/37621-h/37621-h.htm', 'ar', 1000, ARRAY['Romance','Stories','Arabic','Traditional'], 'gutenberg', '37621'),
('قيس وليلى', 'مجهول', 'قصة الحب الخالدة بين قيس وليلى.', 'https://www.gutenberg.org/cache/epub/37622/pg37622.cover.medium.jpg', 'https://www.gutenberg.org/files/37622/37622-h/37622-h.htm', 'ar', 750, ARRAY['Romance','Arabic','Classic','Poetry'], 'gutenberg', '37622'),
('الأغاني والفن في الإسلام', 'الأصفهاني', 'مجموعة من الأغاني والأشعار الإسلامية.', 'https://www.gutenberg.org/cache/epub/37623/pg37623.cover.medium.jpg', 'https://www.gutenberg.org/files/37623/37623-h/37623-h.htm', 'ar', 900, ARRAY['Poetry','Music','Arabic','Culture'], 'gutenberg', '37623'),
('حكايات جحا الظريفة', 'مجهول', 'أشهر طرائف جحا والذي اشتهر بذكائه وفكاهته.', 'https://www.gutenberg.org/cache/epub/37624/pg37624.cover.medium.jpg', 'https://www.gutenberg.org/files/37624/37624-h/37624-h.htm', 'ar', 1000, ARRAY['Comedy','Humor','Arabic','Folk'], 'gutenberg', '37624'),
('المعالقات العشر', 'مجهول', 'أعظم عشر قصائد من الشعر الجاهلي.', 'https://www.gutenberg.org/cache/epub/37625/pg37625.cover.medium.jpg', 'https://www.gutenberg.org/files/37625/37625-h/37625-h.htm', 'ar', 500, ARRAY['Poetry','Epic','Arabic','Classic'], 'gutenberg', '37625');

-- Books with Mixed Languages and Genres
INSERT INTO public.books (title, author, description, cover_url, content_url, language, year, categories, source, external_id) VALUES
('Wuthering Heights', 'Emily Brontë', 'A dark tale of love and revenge on the Yorkshire moors.', 'https://www.gutenberg.org/cache/epub/768/pg768.cover.medium.jpg', 'https://www.gutenberg.org/files/768/768-h/768-h.htm', 'en', 1847, ARRAY['Romance','Gothic','Drama','Fiction'], 'gutenberg', '768'),
('Great Expectations', 'Charles Dickens', 'A boy dreams of becoming a gentleman but finds unexpected love.', 'https://www.gutenberg.org/cache/epub/46/pg46.cover.medium.jpg', 'https://www.gutenberg.org/files/46/46-h/46-h.htm', 'en', 1861, ARRAY['Fiction','Coming-of-age','Social','Classic'], 'gutenberg', '46'),
('The Invisible Man', 'H.G. Wells', 'A scientist discovers the formula for invisibility with dark consequences.', 'https://www.gutenberg.org/cache/epub/5230/pg5230.cover.medium.jpg', 'https://www.gutenberg.org/files/5230/5230-h/5230-h.htm', 'en', 1897, ARRAY['Sci-Fi','Science Fiction','Horror','Mystery'], 'gutenberg', '5230'),
('Vanity Fair', 'William Makepeace Thackeray', 'A novel of manners satirizing British society and ambition.', 'https://www.gutenberg.org/cache/epub/599/pg599.cover.medium.jpg', 'https://www.gutenberg.org/files/599/599-h/599-h.htm', 'en', 1847, ARRAY['Fiction','Social','Satire','Classic'], 'gutenberg', '599');
