// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function cleanEnvValue(value: string | undefined) {
  return value?.trim().replace(/^["']|["']$/g, '');
}

function createDummyClient(message: string): any {
  const dummyHandler: ProxyHandler<any> = {
    get(target, prop, receiver) {
      if (
        prop === 'then' ||
        prop === 'toJSON' ||
        prop === 'constructor' ||
        prop === '__esModule' ||
        prop === 'default' ||
        typeof prop === 'symbol'
      ) {
        return undefined;
      }
      return createDummyClient(message);
    },
    apply() {
      throw new Error(message);
    }
  };
  const dummyFn = () => {};
  return new Proxy(dummyFn, dummyHandler);
}

function createSupabaseClient() {
  // SPA mode: use Vite's import.meta.env only
  const SUPABASE_URL = cleanEnvValue(import.meta.env.VITE_SUPABASE_URL as string);
  const SUPABASE_PUBLISHABLE_KEY = cleanEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Add your Supabase project values to .env.`;
    console.warn(`[Supabase] ${message}`);
    return createDummyClient(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(target, prop, receiver) {
    if (
      prop === 'then' ||
      prop === 'toJSON' ||
      prop === 'constructor' ||
      prop === '__esModule' ||
      prop === 'default' ||
      typeof prop === 'symbol'
    ) {
      return Reflect.get(target, prop, receiver);
    }
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
