// Use this for anything that needs Realtime subscriptions
// Do NOT edit client.ts — it is auto-generated by Lovable

import { supabase } from "./client";

// Patch Realtime transport for Node.js < 22 (SSR/scripts only)
if (typeof window === "undefined") {
  import("ws").then((ws) => {
    (supabase.realtime as any).transport = ws.default;
  });
}

export { supabase };